#!/bin/bash
#####################################
APP_NAME=jacktrip
APP_NAME_QUOTES=\\\"$APP_NAME\\\"
 
######################################
# Created by Chris Chafe
# Modified by Juan-Pablo Caceres to include a make install option to build and RPM, and to make it work with any shell.
 
# QMAKE_CLEAN cleans up ui, killing dependencies involving 
# generated base classes
# don't --> make clean

#rm -r obj
#rm -r moc
#rm $APP_NAME.pro

#echo "progen"

#qmake -project -o $APP_NAME.pro ui/ ../include/
qmake -project -o $APP_NAME.pro

echo "qmake .pro built"

#Create Makefile
qmake -makefile -unix -o Makefile \
"CONFIG+=qt thread warn_on debug" \
"QMAKE_CXXFLAGS+=-Wno-deprecated -pg -g" \
"INCLUDEPATH+=/usr/include/stk $QTDIR/include/qwt" \
"DEFINES+=__LINUX_ALSA__ APP_NAME=$APP_NAME_QUOTES" \
"QMAKE_CLEAN+=$APP_NAME" \
"unix:LIBS+=-Xlinker -rpath $QTDIR/lib -lstk -lasound -ljack -lqwt" \
"unix:TARGET=$APP_NAME" \
"unix:target.path=/usr/bin" \
"unix:INSTALLS+=target" $APP_NAME.pro

echo "done"
