#!/bin/bash
if [[ -t 1 ]]; then
	echo
	echo -e "\033[1;31mIMPORTANT\033[0m"
	echo "The build script is now located in the root jacktrip folder and should"
	echo "be run from there in future. (This script will eventually be removed and"
	echo "is included for compatibility during the transition.)"
	echo
	echo "In future, after cloning the repository with git use the following commands:"
	echo -e "\033[1m$ cd jacktrip"
	echo "$ ./build"
	echo -e "$ cd builddir\033[0m"
	echo
	echo "This will build jacktrip and take you to the build directory."
	echo
	read -n1 -rsp "Press any key to continue the build process..."
	echo
fi
cd ../
./build $@
