#!/bin/bash
## Created by Juan-Pablo Caceres

# Check for Platform
platform='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
    echo "Building on Linux"
    platform='linux'
elif [[ "$unamestr" == 'Darwin' ]]; then
    echo "Building on Mac OS X"
    platform='macosx'
fi

# Set qmake command name
if [[ $platform == 'linux' ]]; then
    QCMD='qtchooser -run-tool=qmake -qt=5'
    QSPEC=linux-g++
elif [[ $platform == 'macosx' ]]; then
    QCMD=qmake
    QSPEC=macx-clang
fi

# Build
if [[ $1 == 'nojack' ]]; then
    echo "Building without Jack"
    $QCMD -spec $QSPEC -config nojack jacktrip.pro
    make clean
    $QCMD -spec $QSPEC -config nojack jacktrip.pro
    make release
else
    $QCMD -spec $QSPEC jacktrip.pro
    make clean
    $QCMD -spec $QSPEC jacktrip.pro
    make release
fi
