on:
  push:
    branches: [dev]
  pull_request:
name: Flatpak Devel
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15
      options: --privileged
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
      with:
        bundle: jacktrip-dev.flatpak
        manifest-path: linux/flatpak/org.jacktrip.JackTrip.Devel.yml
        branch: dev
        cache-key: flatpak-builder-${{ github.sha }}
