name: meson-build
on: [push, pull_request]
jobs:
  skip-duplicates:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["**/README.md", "**/INSTALL*"]'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
  build:
    needs: skip-duplicates
    if: ${{ needs.skip-duplicates.outputs.should_skip != 'true' }}
    runs-on: ${{ matrix.runs-on }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false # don't abort if one of the build failse
      matrix:
        include:
          - name: Linux
            runs-on: ubuntu-20.04
          - name: macOS
            runs-on: macos-10.15
          - name: Windows
            runs-on: windows-2019

    env:
      SRC_PATH: ${{ github.workspace }}/src
      BUILD_PATH: ${{ github.workspace }}/builddir
      QT_VERSION: '5.15.2'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: install dependencies for Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install --yes libpulse-dev libasound2-dev libjack-dev qt5-default qt5-qmake qttools5-dev help2man
          python -m pip install --upgrade pip
          pip install meson ninja
      - name: install dependencies for macOS
        if: runner.os == 'macOS'
        env:
          HOMEBREW_NO_ANALYTICS: 1
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1
        run: |
          brew install qt5 jack meson help2man
          brew link qt5 --force
      - name: install dependencies for Windows
        if: runner.os == 'Windows'
        run: |
          choco install jack
          python -m pip install --upgrade pip
          pip install meson ninja
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
      - name: Cache Qt
        id: cache-qt
        if: runner.os == 'Windows'
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCacheMSVC-${{ env.QT_VERSION }}
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        if: runner.os == 'Windows'
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      - name: build on Linux / macOS
        if: runner.os != 'Windows'
        env:
          DEVELOPER_DIR: '/Applications/Xcode_11.7.app/Contents/Developer' # specify XCode version on macOS
        run: |
          meson --buildtype release $BUILD_PATH
          cd $BUILD_PATH
          meson configure -Ddefault_library=static -Drtaudio=enabled
          meson compile
      - name: build on Windows
        if: runner.os == 'Windows'
        run: |
          meson --buildtype release builddir
          cd builddir
          meson configure -Ddefault_library=static -Drtaudio=enabled
          meson compile
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: JackTrip-${{ matrix.name }} # version number could be added here
          path: ${{ env.BUILD_PATH }}
          retention-days: 30 # remove artifacts after 30 days
